-- AlterTable
ALTER TABLE `Order` ADD COLUMN `email` VARCHAR(191) NULL,
    ADD COLUMN `name` VARCHAR(191) NULL,
    MODIFY `phone` VARCHAR(191) NULL DEFAULT '',
    MODIFY `address` VARCHAR(191) NULL DEFAULT '';
